controller:
  replicaCount: 1
  service:
    type: LoadBalancer
  allowSnippetAnnotations: false
  config:
    limit-req-status-code: "429"
    limit-conn-status-code: "429"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 384Mi
  admissionWebhooks:
    enabled: true
