apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: provenance
  namespace: argocd
spec:
  description: The Provenance application and its monitoring stack
  sourceRepos:
    - https://github.com/YHQZ1/Provenance.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: provenance
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
