export const filingFixture = (overrides = {}) => ({
  financial_year: { start_year: 2026, label: "FY 2026-27", start_date: "2026-04-01", end_date: "2027-03-31" },
  available_years: [2026],
  entity: { company_name: "Acme Packaging", gst_number: "27ABCDE1234F1Z5", pibo_category: ["BRAND_OWNER"] },
  totals: {
    introduced: { by_material: { PET: 1200, HDPE: 300 }, total_kg: 1500 },
    recycled: { by_material: { PET: 400 }, total_kg: 400 },
    collected: { by_material: {}, total_kg: 0 },
  },
  counts: { documents: 2, processing: 0, failed: 0, review: 1, verified: 1, evidence: 0, pending_items: 3, excluded_items: 0 },
  documents: [
    {
      id: "d1",
      filename: "invoice-001.pdf",
      document_type: "purchase_invoice",
      document_type_label: "Purchase invoice",
      stage: "verified",
      status: "VERIFIED",
      effective_date: "2026-05-01",
      date_source: "document",
      items_total: 2,
      items_pending: 0,
      verified_kg: 1500,
    },
  ],
  blockers: [{ key: "review", message: "3 line item(s) are waiting for review.", action: "review" }],
  ready: false,
  status: "OPEN",
  snapshot: null,
  finalization_available: true,
  source_basis: [{ title: "CPCB guidance", url: "https://example.org" }],
  ...overrides,
});

const obligationRow = (category, overrides = {}) => ({
  category,
  introduced_kg: 0,
  pre_consumer_kg: 0,
  supplied_kg: 0,
  epr_quantity_kg: 0,
  epr_target_pct: 100,
  epr_target_source: "default",
  recycling_min_pct: 70,
  recycling_min_source: "default",
  obligation_kg: 0,
  recycling_min_kg: 0,
  recycled_kg: 0,
  shortfall_kg: 0,
  recycling_gap_kg: 0,
  ec_rate_per_kg: null,
  compensation_estimate: null,
  ...overrides,
});

export const obligationFixture = () => ({
  financial_year: { start_year: 2026, label: "FY 2026-27" },
  basis: "current",
  basis_years: ["FY 2026-27"],
  available: true,
  locked: false,
  categories_tracked: true,
  uncategorised_introduced_kg: 0,
  target_source: "Guidelines on EPR for Plastic Packaging, 2022 (Schedule II)",
  rows: [
    obligationRow("CATEGORY_I", {
      introduced_kg: 200,
      pre_consumer_kg: 50,
      supplied_kg: 20,
      epr_quantity_kg: 230,
      recycling_min_pct: 60,
      obligation_kg: 230,
      recycling_min_kg: 138,
      recycled_kg: 100,
      shortfall_kg: 130,
      recycling_gap_kg: 38,
    }),
    obligationRow("CATEGORY_II"),
    obligationRow("CATEGORY_III"),
    obligationRow("CATEGORY_IV", { epr_target_pct: null, epr_target_source: "none", recycling_min_pct: null, recycling_min_source: "none", obligation_kg: null }),
  ],
  totals: {
    introduced_kg: 200,
    epr_quantity_kg: 230,
    obligation_kg: 230,
    recycled_kg: 100,
    shortfall_kg: 130,
    compensation_estimate: null,
  },
});
